### ISSUE TITLE
Fix stalemate

### ISSUE THREAD

**Issue by bkthomps** [bkthomps/Chess#26]
Stalemate is when a player has no legal move at all, not when the king has no legal move.

**Comment by TylerLiu42** [comment]
When a player has no legal moves AND the king is not in check, the game is drawn by stalemate.

**Comment by bkthomps** [comment]
This might not be an issue. Need to test this first.

**Comment by bkthomps** [comment]
After looking at the code and testing, this bug was a false-alarm.
